version: 1.0.{build}
image: Visual Studio 2017
before_build:
    - dotnet restore
    - choco install opencover.portable
    - choco install codecov
    - dotnet tool install --global dotnet-sonarscanner
build:
  verbosity: minimal
build_script:
  - dotnet sonarscanner begin /k:"Baymax" /d:"sonar.host.url=https://sonarqube.com" /d:sonar.login=%SONAR_TOKEN% /d:sonar.organization=cashwu-github /d:sonar.cs.opencover.reportsPaths="coverage.xml"
  - dotnet build
  - dotnet sonarscanner end /d:sonar.login=%SONAR_TOKEN%
after_build:
  - dotnet pack
test_script:
    - OpenCover.Console.exe -register:user -target:"dotnet.exe" -targetargs:"test" -filter:"+[*]* -[*.Tests]*" -output:"coverage.xml" -oldstyle
    - codecov -f "coverage.xml"
artifacts:
    - path : .\Src\Baymax.Tester\bin\Debug\*.nupkg
deploy:
    - provider: NuGet
      server:                  
      api_key:
        secure: YEJhUxU+B84sRzK4ChFAaFwLwC5zhn612E6sFwbu0kNKH20l3AxaH8ouH98Qp4kV 
      skip_symbols: false
      symbol_server:           
      artifact: /.*\.nupkg/
      on:
        branch: master   

environment:
  SONAR_TOKEN:
    secure: BQzWMnMkld7fcxUe3GyBM7+OMpPJJRPULtJfO7qLSNlxZ5G8C2SUIbfUpau1wl2f
